source :rubygems

gem "sinatra"
gem "shotgun"
gem "haml"
gem "sass"
gem "rb-inotify"
gem "livereload"
gem "rack-flash"
gem "dm-core"
gem "dm-validations"
gem "dm-timestamps"
gem "dm-migrations"
gem "dm-serializer"
gem "dm-sqlite-adapter"
gem "mini_magick"
gem "carrierwave-datamapper", :require => "carrierwave/datamapper"
gem "ruby-filemagic"
